---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress-Core"
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths: []
